### ISSUE TITLE
Traefik can't find IP adress for container

### ISSUE THREAD

**Issue by multimill** [anonaddy/docker#103]
Hello guys,

I just tried to use the example from this repository to setup anonaddy with docker. I used the given example in the traefik folder.

But I do encounter the following error again and again no matter what I try:

```
anonaddy    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
anonaddy    | [s6-init] ensuring user provided files have correct perms...exited 0.
anonaddy    | [fix-attrs.d] applying ownership & permissions fixes...
anonaddy    | [fix-attrs.d] done.
anonaddy    | [cont-init.d] executing container initialization scripts...
anonaddy    | [cont-init.d] 00-env: executing...
anonaddy    | [cont-init.d] 00-env: exited 0.
anonaddy    | [cont-init.d] 00-fix-logs.sh: executing...
anonaddy    | [cont-init.d] 00-fix-logs.sh: exited 0.
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: executing...
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: exited 0.
anonaddy    | [cont-init.d] 02-fix-perms.sh: executing...
anonaddy    | Fixing perms...
anonaddy    | [cont-init.d] 02-fix-perms.sh: exited 0.
anonaddy    | [cont-init.d] 10-config.sh: executing...
anonaddy    | ERROR: Rspamd and OpenDKIM/OpenDMARC are mutually exclusive
anonaddy    | [cont-init.d] 10-config.sh: exited 1.
anonaddy    | [cont-finish.d] executing container finish scripts...
anonaddy    | [cont-finish.d] done.
anonaddy    | [s6-finish] waiting for services.
anonaddy    | [s6-finish] sending all processes the TERM signal.
anonaddy    | [s6-finish] sending all processes the KILL signal and exiting.
anonaddy exited with code 1
traefik     | time="2022-01-22T21:35:35Z" level=error msg="service \"anonaddy\" error: unable to find the IP address for the container \"/anonaddy\": the server is ignored" container=anonaddy-home-4c8c65187cf700d3716f2e26c55046af7ab86d4e9c28fe360dd38d092caedd1a providerName=docker
```

I basically do use the default config. I was able to make it work on one test machine but on the other it fails with the given error. 

My config:

<details>
  <summary>My docker-compose.yml (Spoiler)</summary>

  ```
version: "3.5"

services:
  traefik:
    image: traefik:2.5
    container_name: traefik
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=mail@mydomain.com"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--providers.docker"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  db:
    image: mariadb:10.5
    container_name: anonaddy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: always

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - db
      - redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
    volumes:
      - "./data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anonaddy.entrypoints=https"
      - "traefik.http.routers.anonaddy.rule=Host(`mydomain.tld`)"
      - "traefik.http.routers.anonaddy.tls=true"
      - "traefik.http.routers.anonaddy.tls.certresolver=letsencrypt"
      - "traefik.http.routers.anonaddy.tls.domains[0].main=mydomain.tld"
      - "traefik.http.services.anonaddy.loadbalancer.server.port=8000"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    restart: always
  ```
</details>

<details>
  <summary>anonaddy.env</summary>

  ```
TZ=Europe/Berlin
PUID=1000
PGID=1000

MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
LISTEN_IPV6=true
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=http_x_forwarded_for

APP_KEY=base64:TZqfhgtADCJavbKJyA8Iqr3oNRDZZ1b7f91TiNkqM+M=
APP_DEBUG=false
APP_URL=https://mydomain.tld

ANONADDY_RETURN_PATH=bounces@mydomain.tld
ANONADDY_ADMIN_USERNAME=multi
ANONADDY_ENABLE_REGISTRATION=false
ANONADDY_DOMAIN=mydomain.tld
ANONADDY_ALL_DOMAINS=mydomain.tld
ANONADDY_HOSTNAME=mydomain.tld
ANONADDY_DNS_RESOLVER=127.0.0.1
ANONADDY_SECRET=okevkZxAwFqxrlmpepDpBniBenQjHrDiaRoHVTfcrLKABGb8tZf0U
ANONADDY_LIMIT=50
ANONADDY_BANDWIDTH_LIMIT=104857600
ANONADDY_NEW_ALIAS_LIMIT=50
ANONADDY_ADDITIONAL_USERNAME_LIMIT=0
ANONADDY_DKIM_SIGNING_KEY=/data/dkim/mydomain.tld.private
ANONADDY_DKIM_SELECTOR=default

MAIL_FROM_NAME=Spam-Mail
MAIL_FROM_ADDRESS=mail@mydomain.tld

POSTFIX_DEBUG=false
POSTFIX_SMTPD_TLS=false
POSTFIX_SMTP_TLS=false

DKIM_ENABLE=true

RSPAMD_ENABLE=true
RSPAMD_WEB_PASSWORD=E9IxAwoksA4Zv5eiZV
  ```
</details>

EDIT: <details>
  <summary>Whole log incase that helps</summary>

  ```
docker-compose up
Starting anonaddy_redis ... done
Starting anonaddy_db    ... done
Starting traefik        ... done
Starting anonaddy       ... done
Attaching to anonaddy_db, anonaddy_redis, traefik, anonaddy
anonaddy_db | 2022-01-22 21:47:11+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.13+maria~focal started.
anonaddy_db | 2022-01-22 21:47:12+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
anonaddy_db | 2022-01-22 21:47:12+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.13+maria~focal started.
anonaddy_db | 2022-01-22 21:47:12 0 [Note] mysqld (mysqld 10.5.13-MariaDB-1:10.5.13+maria~focal) starting as process 1 ...
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Uses event mutexes
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Number of pools: 1
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
anonaddy_db | 2022-01-22 21:47:12 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Using Linux native AIO
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Completed initialization of buffer pool
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: 128 rollback segments are active.
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Creating shared tablespace for temporary tables
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: 10.5.13 started; log sequence number 45118; transaction id 20
anonaddy_db | 2022-01-22 21:47:12 0 [Note] Plugin 'FEEDBACK' is disabled.
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
anonaddy_db | 2022-01-22 21:47:12 0 [Note] InnoDB: Buffer pool(s) load completed at 220122 21:47:12
anonaddy_db | 2022-01-22 21:47:13 0 [Note] Server socket created on IP: '::'.
anonaddy_db | 2022-01-22 21:47:13 0 [Warning] 'proxies_priv' entry '@% root@dcfe60fb80a3' ignored in --skip-name-resolve mode.
anonaddy_db | 2022-01-22 21:47:13 0 [Note] Reading of all Master_info entries succeeded
anonaddy_db | 2022-01-22 21:47:13 0 [Note] Added new Master_info '' to hash table
anonaddy_db | 2022-01-22 21:47:13 0 [Note] mysqld: ready for connections.
anonaddy_db | Version: '10.5.13-MariaDB-1:10.5.13+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
anonaddy_redis | 1:C 22 Jan 21:47:11.754 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
anonaddy_redis | 1:C 22 Jan 21:47:11.754 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
anonaddy_redis | 1:C 22 Jan 21:47:11.754 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
anonaddy_redis | 1:M 22 Jan 21:47:11.756 * Running mode=standalone, port=6379.
anonaddy_redis | 1:M 22 Jan 21:47:11.756 # Server initialized
anonaddy_redis | 1:M 22 Jan 21:47:11.756 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
anonaddy_redis | 1:M 22 Jan 21:47:11.757 * DB loaded from disk: 0.001 seconds
anonaddy_redis | 1:M 22 Jan 21:47:11.757 * Ready to accept connections
traefik     | time="2022-01-22T21:47:12Z" level=info msg="Configuration loaded from flags."
traefik     | time="2022-01-22T21:47:12Z" level=info msg="Traefik version 2.5.7 built on 2022-01-20T16:16:23Z"
traefik     | time="2022-01-22T21:47:12Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
traefik     | time="2022-01-22T21:47:12Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
traefik     | time="2022-01-22T21:47:12Z" level=info msg="Starting provider *traefik.Provider {}"
traefik     | time="2022-01-22T21:47:12Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"swarmModeRefreshSeconds\":\"15s\"}"
traefik     | time="2022-01-22T21:47:12Z" level=info msg="Starting provider *acme.ChallengeTLSALPN {\"Timeout\":4000000000}"
traefik     | time="2022-01-22T21:47:12Z" level=info msg="Starting provider *acme.Provider {\"email\":\"mail@mydomain.tld\",\"caServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"storage\":\"acme.json\",\"keyType\":\"RSA4096\",\"httpChallenge\":{\"entryPoint\":\"http\"},\"ResolverName\":\"letsencrypt\",\"store\":{},\"TLSChallengeProvider\":{\"Timeout\":4000000000},\"HTTPChallengeProvider\":{}}"
traefik     | time="2022-01-22T21:47:12Z" level=info msg="Testing certificate renew..." providerName=letsencrypt.acme
anonaddy    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
anonaddy    | [s6-init] ensuring user provided files have correct perms...exited 0.
anonaddy    | [fix-attrs.d] applying ownership & permissions fixes...
anonaddy    | [fix-attrs.d] done.
anonaddy    | [cont-init.d] executing container initialization scripts...
anonaddy    | [cont-init.d] 00-env: executing...
anonaddy    | [cont-init.d] 00-env: exited 0.
anonaddy    | [cont-init.d] 00-fix-logs.sh: executing...
anonaddy    | [cont-init.d] 00-fix-logs.sh: exited 0.
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: executing...
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: exited 0.
anonaddy    | [cont-init.d] 02-fix-perms.sh: executing...
anonaddy    | Fixing perms...
anonaddy    | [cont-init.d] 02-fix-perms.sh: exited 0.
anonaddy    | [cont-init.d] 10-config.sh: executing...
anonaddy    | ERROR: Rspamd and OpenDKIM/OpenDMARC are mutually exclusive
anonaddy    | [cont-init.d] 10-config.sh: exited 1.
anonaddy    | [cont-finish.d] executing container finish scripts...
anonaddy    | [cont-finish.d] done.
anonaddy    | [s6-finish] waiting for services.
anonaddy    | [s6-finish] sending all processes the TERM signal.
anonaddy    | [s6-finish] sending all processes the KILL signal and exiting.
traefik     | time="2022-01-22T21:47:18Z" level=error msg="service \"anonaddy\" error: unable to find the IP address for the container \"/anonaddy\": the server is ignored" container=anonaddy-home-4c8c65187cf700d3716f2e26c55046af7ab86d4e9c28fe360dd38d092caedd1a providerName=docker
anonaddy    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
anonaddy    | [s6-init] ensuring user provided files have correct perms...exited 0.
anonaddy    | [fix-attrs.d] applying ownership & permissions fixes...
anonaddy    | [fix-attrs.d] done.
anonaddy    | [cont-init.d] executing container initialization scripts...
anonaddy    | [cont-init.d] 00-env: executing...
anonaddy    | [cont-init.d] 00-env: exited 0.
anonaddy    | [cont-init.d] 00-fix-logs.sh: executing...
anonaddy    | [cont-init.d] 00-fix-logs.sh: exited 0.
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: executing...
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: exited 0.
anonaddy    | [cont-init.d] 02-fix-perms.sh: executing...
anonaddy    | Fixing perms...
anonaddy    | [cont-init.d] 02-fix-perms.sh: exited 0.
anonaddy    | [cont-init.d] 10-config.sh: executing...
anonaddy    | ERROR: Rspamd and OpenDKIM/OpenDMARC are mutually exclusive
anonaddy    | [cont-init.d] 10-config.sh: exited 1.
anonaddy    | [cont-finish.d] executing container finish scripts...
anonaddy    | [cont-finish.d] done.
anonaddy    | [s6-finish] waiting for services.
anonaddy    | [s6-finish] sending all processes the TERM signal.
anonaddy    | [s6-finish] sending all processes the KILL signal and exiting.
anonaddy exited with code 1
anonaddy    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
anonaddy    | [s6-init] ensuring user provided files have correct perms...exited 0.
anonaddy    | [fix-attrs.d] applying ownership & permissions fixes...
anonaddy    | [fix-attrs.d] done.
anonaddy    | [cont-init.d] executing container initialization scripts...
anonaddy    | [cont-init.d] 00-env: executing...
anonaddy    | [cont-init.d] 00-env: exited 0.
anonaddy    | [cont-init.d] 00-fix-logs.sh: executing...
anonaddy    | [cont-init.d] 00-fix-logs.sh: exited 0.
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: executing...
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: exited 0.
anonaddy    | [cont-init.d] 02-fix-perms.sh: executing...
anonaddy    | Fixing perms...
anonaddy    | [cont-init.d] 02-fix-perms.sh: exited 0.
anonaddy    | [cont-init.d] 10-config.sh: executing...
anonaddy    | ERROR: Rspamd and OpenDKIM/OpenDMARC are mutually exclusive
anonaddy    | [cont-init.d] 10-config.sh: exited 1.
anonaddy    | [cont-finish.d] executing container finish scripts...
anonaddy    | [cont-finish.d] done.
anonaddy    | [s6-finish] waiting for services.
anonaddy    | [s6-finish] sending all processes the TERM signal.
anonaddy    | [s6-finish] sending all processes the KILL signal and exiting.
anonaddy exited with code 1
anonaddy    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
anonaddy    | [s6-init] ensuring user provided files have correct perms...exited 0.
anonaddy    | [fix-attrs.d] applying ownership & permissions fixes...
anonaddy    | [fix-attrs.d] done.
anonaddy    | [cont-init.d] executing container initialization scripts...
anonaddy    | [cont-init.d] 00-env: executing...
anonaddy    | [cont-init.d] 00-env: exited 0.
anonaddy    | [cont-init.d] 00-fix-logs.sh: executing...
anonaddy    | [cont-init.d] 00-fix-logs.sh: exited 0.
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: executing...
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: exited 0.
anonaddy    | [cont-init.d] 02-fix-perms.sh: executing...
anonaddy    | Fixing perms...
anonaddy    | [cont-init.d] 02-fix-perms.sh: exited 0.
anonaddy    | [cont-init.d] 10-config.sh: executing...
anonaddy    | ERROR: Rspamd and OpenDKIM/OpenDMARC are mutually exclusive
anonaddy    | [cont-init.d] 10-config.sh: exited 1.
anonaddy    | [cont-finish.d] executing container finish scripts...
anonaddy    | [cont-finish.d] done.
anonaddy    | [s6-finish] waiting for services.
anonaddy    | [s6-finish] sending all processes the TERM signal.
anonaddy    | [s6-finish] sending all processes the KILL signal and exiting.
anonaddy exited with code 1
traefik     | time="2022-01-22T21:47:34Z" level=error msg="service \"anonaddy\" error: unable to find the IP address for the container \"/anonaddy\": the server is ignored" providerName=docker container=anonaddy-home-4c8c65187cf700d3716f2e26c55046af7ab86d4e9c28fe360dd38d092caedd1a
anonaddy    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
anonaddy    | [s6-init] ensuring user provided files have correct perms...exited 0.
anonaddy    | [fix-attrs.d] applying ownership & permissions fixes...
anonaddy    | [fix-attrs.d] done.
anonaddy    | [cont-init.d] executing container initialization scripts...
anonaddy    | [cont-init.d] 00-env: executing...
anonaddy    | [cont-init.d] 00-env: exited 0.
anonaddy    | [cont-init.d] 00-fix-logs.sh: executing...
anonaddy    | [cont-init.d] 00-fix-logs.sh: exited 0.
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: executing...
anonaddy    | [cont-init.d] 01-fix-uidgid.sh: exited 0.
anonaddy    | [cont-init.d] 02-fix-perms.sh: executing...
anonaddy    | Fixing perms...
anonaddy    | [cont-init.d] 02-fix-perms.sh: exited 0.
anonaddy    | [cont-init.d] 10-config.sh: executing...
anonaddy    | ERROR: Rspamd and OpenDKIM/OpenDMARC are mutually exclusive
anonaddy    | [cont-init.d] 10-config.sh: exited 1.
anonaddy    | [cont-finish.d] executing container finish scripts...
anonaddy    | [cont-finish.d] done.
anonaddy    | [s6-finish] waiting for services.
anonaddy    | [s6-finish] sending all processes the TERM signal.
anonaddy    | [s6-finish] sending all processes the KILL signal and exiting.
anonaddy exited with code 1
traefik     | time="2022-01-22T21:47:39Z" level=error msg="service \"anonaddy\" error: unable to find the IP address for the container \"/anonaddy\": the server is ignored" providerName=docker container=anonaddy-home-4c8c65187cf700d3716f2e26c55046af7ab86d4e9c28fe360dd38d092caedd1a

  ```
</details>

Maybe you guys have an idea where to look at? Thanks in advance!
