### ISSUE TITLE
500s from `POST /api/v1/aliases`

### ISSUE THREAD

**Issue by necropolina** [anonaddy/docker#110]
### Behaviour
Everything seems to be working fine, except for create aliases. Traefik is proxying the webui, I can add users, verification emails get sent, I can add custom domains and verify TXT records, etc. But creating aliases errors out.

#### Steps to reproduce this issue
1. run using the compose/env below
2. Log in and attempt to create aliases

#### Expected behaviour
Aliases get created

#### Actual behaviour
The `POST /api/v1/aliases` endpoint is 500ing

### Configuration

* Docker version (type `docker --version`) : `Docker version 20.10.12, build e91ed57`
* Docker compose version if applicable (type `docker-compose --version`) :  `docker-compose version 1.29.2, build 5becea4c`
* Platform (Debian 9, Ubuntu 18.04, ...) : `Ubuntu 21.04`
* System info (type `uname -a`) :  `Linux 1312 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### anonaddy.env
```
TZ=America/New_York
PUID=1000
PGID=1000

MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=http_x_forwarded_for

APP_KEY=base64:notreallythekey2376rgq93fhfh0sf4087=
APP_DEBUG=false
APP_URL=https://mail.example.com

ANONADDY_RETURN_PATH=bounces@example.com
ANONADDY_ADMIN_USERNAME=lina
ANONADDY_ENABLE_REGISTRATION=false
ANONADDY_DOMAIN=example.com
ANONADDY_ALL_DOMAINS=example.com
ANONADDY_HOSTNAME=mail.example.com
ANONADDY_DNS_RESOLVER=127.0.0.1
ANONADDY_SECRET=notmysecrethbafiuysh498f7rbfiudrg8e4ughesignsojn0fu=4tih349
ANONADDY_LIMIT=200
ANONADDY_BANDWIDTH_LIMIT=2097152000
ANONADDY_NEW_ALIAS_LIMIT=25
ANONADDY_ADDITIONAL_USERNAME_LIMIT=1000

MAIL_FROM_NAME=Anonalina
MAIL_FROM_ADDRESS=anonbot@mail.example.com

POSTFIX_DEBUG=false
POSTFIX_SMTPD_TLS=false
POSTFIX_SMTP_TLS=false

DKIM_ENABLE=true
DMARC_ENABLE=true
```

### Docker compose
```
version: "3.5"

services:
  traefik:
    image: traefik
    container_name: traefik
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    command:
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.myresolver.acme.email=${CLOUDFLARE_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.docker"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./configs/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  anonaddy_db:
    image: mariadb:10.5
    container_name: anonaddy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./configs/anonaddy/db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always

  anonaddy_redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: always

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - anonaddy_db
      - anonaddy_redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
    volumes:
      - "./configs/anonaddy/data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anonaddy.entrypoints=https"
      - "traefik.http.routers.anonaddy.rule=Host(`mail.example.com`)"
      - "traefik.http.routers.anonaddy.tls=true"
      - "traefik.http.routers.anonaddy.tls.certresolver=myresolver"
      - "traefik.http.services.anonaddy.loadbalancer.server.port=8000"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_HOST=anonaddy_db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    restart: always
```

### Logs
```
anonaddy                | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
anonaddy                | [s6-init] ensuring user provided files have correct perms...exited 0.
anonaddy                | [fix-attrs.d] applying ownership & permissions fixes...
anonaddy                | [fix-attrs.d] done.
anonaddy                | [cont-init.d] executing container initialization scripts...
anonaddy                | [cont-init.d] 00-env: executing... 
anonaddy                | [cont-init.d] 00-env: exited 0.
anonaddy                | [cont-init.d] 00-fix-logs.sh: executing... 
anonaddy                | [cont-init.d] 00-fix-logs.sh: exited 0.
anonaddy                | [cont-init.d] 01-fix-uidgid.sh: executing... 
anonaddy                | [cont-init.d] 01-fix-uidgid.sh: exited 0.
anonaddy                | [cont-init.d] 02-fix-perms.sh: executing... 
anonaddy                | Fixing perms...
anonaddy                | [cont-init.d] 02-fix-perms.sh: exited 0.
anonaddy                | [cont-init.d] 10-config.sh: executing... 
anonaddy                | Setting timezone to America/New_York...
anonaddy                | Initializing files and folders
anonaddy                | Checking database connection...
anonaddy                | Waiting 60s for database to be ready...
anonaddy                | Database ready!
anonaddy                | [cont-init.d] 10-config.sh: exited 0.
anonaddy                | [cont-init.d] 11-config-php.sh: executing... 
anonaddy                | Init PHP extensions
anonaddy                | Setting PHP-FPM configuration
anonaddy                | Setting PHP INI configuration
anonaddy                | Setting OpCache configuration
anonaddy                | [cont-init.d] 11-config-php.sh: exited 0.
anonaddy                | [cont-init.d] 12-config-nginx.sh: executing... 
anonaddy                | Setting Nginx configuration
anonaddy                | [cont-init.d] 12-config-nginx.sh: exited 0.
anonaddy                | [cont-init.d] 13-config-anonaddy.sh: executing... 
anonaddy                | Creating AnonAddy env file
anonaddy                | Trust all proxies
anonaddy                | Copied File [/vendor/fideloper/proxy/config/trustedproxy.php] To [/config/trustedproxy.php]
anonaddy                | Publishing complete.
anonaddy                | [cont-init.d] 13-config-anonaddy.sh: exited 0.
anonaddy                | [cont-init.d] 14-config-rspamd.sh: executing... 
anonaddy                | INFO: Rspamd service disabled.
anonaddy                | [cont-init.d] 14-config-rspamd.sh: exited 0.
anonaddy                | [cont-init.d] 15-config-opendkim.sh: executing... 
anonaddy                | Copying OpenDKIM private key
anonaddy                | Setting OpenDKIM configuration
anonaddy                | Setting OpenDKIM trusted hosts
anonaddy                | Setting OpenDKIM signing table
anonaddy                | Setting OpenDKIM key table
anonaddy                | [cont-init.d] 15-config-opendkim.sh: exited 0.
anonaddy                | [cont-init.d] 16-config-opendmarc.sh: executing... 
anonaddy                | Setting OpenDMARC configuration
anonaddy                | [cont-init.d] 16-config-opendmarc.sh: exited 0.
anonaddy                | [cont-init.d] 17-config-postfix.sh: executing... 
anonaddy                | Setting Postfix master configuration
anonaddy                | Setting Postfix main configuration
anonaddy                | Setting Postfix milter configuration
anonaddy                | Creating Postfix virtual alias domains and subdomains configuration
anonaddy                | Creating Postfix recipient access configuration
anonaddy                | Checking Postfix hostname
anonaddy                | myhostname = mail.example.com
anonaddy                | Creating check_access stored procedure
anonaddy                | [cont-init.d] 17-config-postfix.sh: exited 0.
anonaddy                | [cont-init.d] 50-svc-main.sh: executing... 
anonaddy                | DB migration
anonaddy                | Nothing to migrate.
anonaddy                | Clear cache
anonaddy                | Application cache cleared!
anonaddy                | Configuration cache cleared!
anonaddy                | Configuration cached successfully!
anonaddy                | Compiled views cleared!
anonaddy                | Blade templates cached successfully!
anonaddy                | Route cache cleared!
anonaddy                | Routes cached successfully!
anonaddy                | Broadcasting queue restart signal.
anonaddy                | [cont-init.d] 50-svc-main.sh: exited 0.
anonaddy                | [cont-init.d] 60-svc-opendkim.sh: executing... 
anonaddy                | [cont-init.d] 60-svc-opendkim.sh: exited 0.
anonaddy                | [cont-init.d] 61-svc-opendmarc.sh: executing... 
anonaddy                | [cont-init.d] 61-svc-opendmarc.sh: exited 0.
anonaddy                | [cont-init.d] 62-svc-rspamd.sh: executing... 
anonaddy                | INFO: Rspamd service disabled.
anonaddy                | [cont-init.d] 62-svc-rspamd.sh: exited 0.
anonaddy                | [cont-init.d] 63-svc-postfix.sh: executing... 
anonaddy                | [cont-init.d] 63-svc-postfix.sh: exited 0.
anonaddy                | [cont-init.d] 80-svc-cron.sh: executing... 
anonaddy                | Fixing crontabs permissions...
anonaddy                | [cont-init.d] 80-svc-cron.sh: exited 0.
anonaddy                | [cont-init.d] 99-clean.sh: executing... 
anonaddy                | [cont-init.d] 99-clean.sh: exited 0.
anonaddy                | [cont-init.d] ~-socklog: executing... 
anonaddy                | [cont-init.d] ~-socklog: exited 0.
anonaddy                | [cont-init.d] done.
anonaddy                | [services.d] starting services
anonaddy                | 2022/02/10 17:10:15 [notice] 834#834: using the "epoll" event method
anonaddy                | 2022/02/10 17:10:15 [notice] 834#834: nginx/1.20.2
anonaddy                | 2022/02/10 17:10:15 [notice] 834#834: OS: Linux 5.11.0-49-generic
anonaddy                | 2022/02/10 17:10:15 [notice] 834#834: getrlimit(RLIMIT_NOFILE): 1048576:1048576
anonaddy                | 2022/02/10 17:10:15 [notice] 834#834: start worker processes
anonaddy                | 2022/02/10 17:10:15 [notice] 834#834: start worker process 853
anonaddy                | 2022/02/10 17:10:15 [notice] 834#834: start worker process 854
anonaddy                | crond: crond (busybox 1.34.1) started, log level 8
anonaddy                | Feb 10 17:10:15 mail postfix[832]: Postfix is running with backwards-compatible default settings
anonaddy                | Feb 10 17:10:15 mail postfix[832]: See http://www.postfix.org/COMPATIBILITY_README.html for details
anonaddy                | Feb 10 17:10:15 mail postfix[832]: To disable backwards compatibility use "postconf compatibility_level=3.6" and "postfix reload"
anonaddy                | [services.d] done.
anonaddy                | mail.info: Feb 10 22:10:15 opendkim[839]: OpenDKIM Filter v2.11.0 starting (args: -f -u opendkim -x /etc/opendkim/opendkim.conf)
anonaddy                | mail.info: Feb 10 22:10:15 opendmarc[838]: OpenDMARC Filter v1.4.1 starting (args: -f -u opendmarc -c /etc/opendmarc/opendmarc.conf)
anonaddy                | mail.info: Feb 10 22:10:15 opendmarc[838]: additional trusted authentication services: mail.example.com
anonaddy                | [10-Feb-2022 17:10:15] NOTICE: fpm is running, pid 836
anonaddy                | [10-Feb-2022 17:10:15] NOTICE: ready to handle connections
anonaddy                | Feb 10 17:10:15 mail postfix/postfix-script[1030]: starting the Postfix mail system
anonaddy                | Feb 10 17:10:15 mail postfix/master[1031]: daemon started -- version 3.6.4, configuration /etc/postfix
```
