### ISSUE TITLE
Unable to user DB_USERNAME_FILE variable

### ISSUE THREAD

**Issue by buxm** [anonaddy/docker#132]
### Behaviour
When `DB_USERNAME_FILE` environment is set (but not `DB_USERNAME`), running the container results in the Anonaddy app to terminate. 
The following line is logged in the Anonaddy docker container logs:
```
error: both DB_USERNAME and DB_USERNAME_FILE are set (but are exclusive)
```

#### Steps to reproduce this issue

1. create a docker compose file defining a `db_user` secret containing the DB username and the anonaddy service referring that secret
2. set the environment variable `DB_USERNAME_FILE=/run/secrets/db_user`
3. deploy the container/stack

#### Expected behaviour

The Anonaddy container starts and successfully connects to the database

#### Actual behaviour

The Anonaddy container starts, logs the following line in the logs:
```
error: both DB_USERNAME and DB_USERNAME_FILE are set (but are exclusive)
```
and terminates

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.17, build 100c701
* Docker compose version if applicable (type `docker-compose --version`) :  Docker Compose version v2.6.0
* Platform (Debian 9, Ubuntu 18.04, ...) : Oracle Linux 8.5 
* System info (type `uname -a`) : 'Linux email4ward01 5.4.17-2136.308.9.el8uek.x86_64 #2 SMP Mon Jun 13 20:36:40 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux'
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...
```
services:
  db:
    image: mariadb:latest
    container_name: anonaddy_db
...
  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - db
      - redis

    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 11334
        published: 11334
        protocol: tcp
    volumes:
      - "/docker/data/Anonaddy/data:/data"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_DATABASE=anonaddy"
      - "DB_USERNAME_FILE=/run/secrets/db_user"
      - "DB_PASSWORD_FILE=/run/secrets/db_password"
      
    networks:
      - db
      - redis
      
    secrets:
      - source: app_key
        mode: 0400
      - source: anonaddy_secret
        mode: 0400
      - source: db_user
        mode: 0400
      - source: db_password
        mode: 0400
secrets:
    db_user:
      file: db_user.txt
    db_password:
      file: db_password.txt
    app_key:
      file: app_key_file.txt
    anonaddy_secret:
      file: anonaddy_secret_file.txt
```
anonaddy.env does NOT contain `DB_USER` variable
