### ISSUE TITLE
Unable to start app container if DB has root password set

### ISSUE THREAD

**Issue by buxm** [anonaddy/docker#135]
### Behaviour
If the MariaDB container is set with a `MYSQL_ROOT_PASSWORD` instead of `MYSQL_ALLOW_EMPTY_PASSWORD=yes`, the Anonaddy docker container won't start. However, my understanding is that the Anonaddy docker container should only need the `MYSQL_USER` (=`DB_USERNAME` in anonaddy container) to setup its database. In fact the MariaDB container should create the `MYSQL_USER` with full privileges on the `MYSQL_DATABASE` (=`DB_DATABASE` in Anonaddy container). I understand that running a production service with `MYSQL_ALLOW_EMPTY_PASSWORD=yes` is not supposed to be secure.

#### Steps to reproduce this issue

1. Create a new set up from scratch, with empty data folders for both MariaDB and Anonaddy
2. In the Docker compose file, populate the following vars for MariaDB service: `MYSQL_ROOT_PASSWORD=root_password` and `MYSQL_DATABASE`, `MYSQL_USER` and `MYSQL_PASSWORD` as in the examples. But DO NOT populate `MYSQL_ALLOW_EMPTY_PASSWORD=yes`
3. In the Docker compose file, populate the following vars for Anonaddy service: `DB_DATABASE`, `DB_USERNAME` and `DB_PASSWORD` with the same values as `MYSQL_DATABASE`, `MYSQL_USER` and `MYSQL_PASSWORD`
4. `docker compose up -d`

#### Expected behaviour

All services starts normally and data folders are populated

#### Actual behaviour

MariaDB container starts successfully. Its logs say:
```
[Note] mysqld: ready for connections.
Version: '10.8.3-MariaDB-1:10.8.3+maria~jammy'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```
Anonaddy container fails to start. Its logs say:
```
...
Checking database connection...
Waiting 60s for database to be ready...
ERROR: Failed to connect to database on anonaddy_db
[cont-init.d] 10-config.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
...
```
At the same time of `ERROR: Failed to connect to database on anonaddy_db`, the following message appears in MariaDB container's logs:
`[Warning] Access denied for user 'root'@'localhost' (using password: YES)`

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.17, build 100c701
* Docker compose version if applicable (type `docker-compose --version`) : Docker Compose version v2.6.0
* Platform (Debian 9, Ubuntu 18.04, ...) : Oracle Linux 8.5
* System info (type `uname -a`) :  'Linux email4ward01 5.4.17-2136.308.9.el8uek.x86_64 #2 SMP Mon Jun 13 20:36:40 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux'
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...
```
version: "3.5"

networks:
  db:
  redis:

services:
  db:
    image: mariadb:latest
    container_name: anonaddy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "/docker/data/Anonaddy/db:/var/lib/mysql"
    environment:
      - TZ=Europe/Rome
      - "MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password"
      #- "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=anonaddy"
      - "MYSQL_USER_FILE=/run/secrets/db_user"
      - "MYSQL_PASSWORD_FILE=/run/secrets/db_password"
      
    secrets:
      - source: db_root_password
        mode: 0400      
      - source: db_user
        mode: 0400
      - source: db_password
        mode: 0400
    
    networks:
      - db
  redis:
    image: redis:latest
    container_name: anonaddy_redis
    networks:
      - redis

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - db
      - redis
      
    ports:
      - target: 25
        published: 25
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 11334
        published: 11334
        protocol: tcp
    volumes:
      - "/docker/data/Anonaddy/data:/data"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_DATABASE=anonaddy"
      - "DB_USERNAME=anonaddy"
      - "DB_PASSWORD_FILE=/run/secrets/db_password"
      
    networks:
      - db
      - redis
      
    secrets:
      - source: app_key
        mode: 0400
      - source: anonaddy_secret
        mode: 0400
      - source: db_password
        mode: 0400
      
secrets:
    db_root_password:
      file: db_root_password.txt
    db_user:
      file: db_user.txt
    db_password:
      file: db_password.txt
    app_key:
      file: app_key_file.txt
    anonaddy_secret:
      file: anonaddy_secret_file.txt
```
### Docker info

```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:11 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:29 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[opc@email4ward01 anonaddy]$ docker --version
Docker version 20.10.17, build 100c701
[opc@email4ward01 anonaddy]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 18
  Running: 6
  Paused: 0
  Stopped: 12
 Images: 12
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: loex9109qngrpwn7gt7j6ej79
  Is Manager: true
  ClusterID: kqyjww50b9jqw10avsbcf6ial
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.128.231
  Manager Addresses:
   10.0.0.114:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.17-2136.308.9.el8uek.x86_64
 Operating System: Oracle Linux Server 8.6
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 680.4MiB
 Name: email4ward01
 ID: OAMQ:R4WF:PJXN:3X2N:BQY7:KSGV:HMEM:OKC2:V2MI:E6BZ:C7AY:RZ5D
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
