### ISSUE TITLE
'file exists' error on start up only

### ISSUE THREAD

**Issue by youngt2** [anonaddy/docker#151]
### Behaviour
On a system restart I get the following error in my anonaddy log:

`cp: can't create '/data/storage': File exists` and the container exits.

If I `docker stop anonaddy` `docker remove anonaddy` and then start with my normal docker compose command I do not see this error.
#### Steps to reproduce this issue

1. restart pc?

#### Expected behaviour

Anonaddy should start normally even on system restart

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.17, build 100c701
* Docker compose version if applicable (type `docker-compose --version`) : Docker Compose version v2.6.0
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 22.04 LTS
* System info (type `uname -a`) : 5.15.0-1013-gcp # 18-Ubuntu SMP Sun Jul 3 04:59:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

<details><summary>anonaddy compose section</summary>
<p>

```
  anonaddy:
    image: anonaddy/anonaddy:latest
    depends_on:
      - db
      - redis
    container_name: anonaddy
    labels:
      - traefik.enable=true
      - traefik.docker.network=mail
      - traefik.http.routers.anonaddy.entrypoints=websecure
      - traefik.http.routers.anonaddy.rule=Host(`anonaddy.$DOMAINNAME`)
      - traefik.http.routers.anonaddy.service=anonaddy-svc
      - traefik.http.services.anonaddy-svc.loadbalancer.server.port=8000
      #- traefik.http.routers.anonaddy.middlewares=secHeaders@file
      - traefik.http.routers.spam.entrypoints=websecure
      - traefik.http.routers.spam.rule=Host(`spam.$DOMAINNAME`)
      - traefik.http.routers.spam.service=spam-svc
      - traefik.http.services.spam-svc.loadbalancer.server.port=11334
      #- traefik.http.routers.spam.middlewares=secHeaders@file
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    ports:
      - target: 25
        published: 25
        protocol: tcp
    volumes:
      - "./aa/data:/data"
    restart: unless-stopped
```

</p>
</details>

<details><summary>### Docker info</summary>
<p>

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-1013-gcp
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 967.6MiB
 Name: (my hostname)
 ID: SUO5:R2FD:QJMS:RRIC:XFEC:S4QH:YZRB:Z5R4:RCCB:OEF3:BLDZ:FXWA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

</p>
</details>

### Logs

The line `cp: can't create '/data/storage': File exists` is the only unusually line I have noticed.
