### ISSUE TITLE
No laravel logs written

### ISSUE THREAD

**Issue by hnrd** [anonaddy/docker#178]
#### Steps to reproduce this issue

1. Upgrade from 0.12.3 -> 0.13.7
2. Try to add new recipient / alias via web interface (results in error)
3. Search for laravel logfile - doesn't exist

#### Expected behaviour

> After upgrading modifiying settings via web interface such as adding recipients or aliases result in a small notification "Error An error has occurred, please try again later" in the lower corner. I'd expect to find a stacktrace in laravel.log

#### Actual behaviour

> There is no logfile written. The only logs that existed where written from the old version before upgrading. Removing them results in an empty log folder.

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.18, build b40c2f6
* Docker compose version if applicable (type `docker-compose --version`) :  docker-compose version 1.29.2, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 11.5
* System info (type `uname -a`) : `Linux worker04 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

docker-compose:
```
version: "2.1"

networks:
  dmz:
    external: true
  back:

services:
  redis:
    image: redis:4.0-alpine
    restart: always
    networks:
      - back

  anonaddy:
    image: anonaddy/anonaddy:0.13.7
    dns: 172.27.123.1
    depends_on:
      - redis
    ports:
      - "2525:25/tcp"
      - "172.27.123.14:11334:11334"
    volumes:
      - "data:/data"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_HOST=172.27.123.14"  # this is a local haproxy loadbalancing a mariadb cluster
      - "DB_PORT=3307"
      - "DB_DATABASE=anonaddy"
      - "DB_USERNAME=anonaddy"
      - "DB_PASSWORD=hunter2"
      - "REDIS_HOST=redis"
      - "APP_NAME=foobar"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dmz"
      - "traefik.http.routers.anonaddy.rule=Host(`foobar.example.com`)"
      - "traefik.http.services.anonaddy.loadbalancer.server.port=8000"
      - "traefik.http.routers.anonaddy.tls=true"
      - "traefik.http.routers.anonaddy.tls.certresolver=buypass"
      - "traefik.http.routers.anonaddy.service=anonaddy"
    networks:
      - dmz
      - back
    restart: always

volumes:
  data:
    labels:
      restic.backup: true
```

anonaddy.env:
```
TZ=Europe/Berlin
PUID=1000
PGID=1000

MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

APP_KEY=base64:hunter2=
APP_DEBUG=true
APP_URL=https://foobar.example.com

ANONADDY_ADDITIONAL_USERNAME_LIMIT=3
ANONADDY_ADMIN_USERNAME=leroy
ANONADDY_ALL_DOMAINS=example.com,example.org
ANONADDY_BANDWIDTH_LIMIT=104857600
ANONADDY_DNS_RESOLVER=172.27.123.1
ANONADDY_DOMAIN=example.com
ANONADDY_ENABLE_REGISTRATION=false
ANONADDY_HOSTNAME=worker04.example.com
ANONADDY_LIMIT=200
ANONADDY_NEW_ALIAS_LIMIT=10
ANONADDY_RETURN_PATH=bounces@example.com
ANONADDY_SECRET="hunter2=="

MAIL_FROM_NAME=AnonAddy
MAIL_FROM_ADDRESS=anonaddy@example.com
MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_ENCRYPTION=null

POSTFIX_DEBUG=true
POSTFIX_SMTPD_TLS=false

POSTFIX_SMTP_TLS=true
POSTFIX_RELAYHOST=mx02.example.com

RSPAMD_ENABLE=true
RSPAMD_WEB_PASSWORD=hunter2
```

### Docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)

Server:
 Containers: 14
  Running: 13
  Paused: 0
  Stopped: 1
 Images: 14
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-13-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.89GiB
 Name: worker04
 ID: HR3N:6CGK:NKYE:J4KM:K3X3:IPAD:NHUR:P7AH:LLYK:IEPU:LM3L:KQWA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Logs

(Logs show container start and try to toggle encryption on a recipient)
Github threw an error for the issue being to large, so I'll attach the log
