### ISSUE TITLE
Error does not connect to DB

### ISSUE THREAD

**Issue by ririko5834** [anonaddy/docker#185]
I have created stack on portainer but it does not work. 
![image](https://user-images.githubusercontent.com/64729293/192981018-fca69e23-e574-4e29-8ee2-30211b72159c.png)

```
version: "3.5"

services:
  db:
    image: mariadb:10.5
    container_name: anonaddy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: always

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - db
      - redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - "./data:/data"
  #  env_file:
  #    - "./anonaddy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    restart: always
```
![image](https://user-images.githubusercontent.com/64729293/192981172-7384c9c5-7ca1-4f87-90ea-fb4093c570c4.png)
![image](https://user-images.githubusercontent.com/64729293/192981608-7c6ff0c0-df20-4556-b332-1c8c43e01140.png)

anonaddy logs:
![image](https://user-images.githubusercontent.com/64729293/192981270-93783702-78fe-412a-8b71-ff99b4e970bd.png)

db logs: 
![image](https://user-images.githubusercontent.com/64729293/192981372-18ece077-39ad-4d5b-9554-6842646a9304.png)

Please help me
