### ISSUE TITLE
Docker compose errors

### ISSUE THREAD

**Issue by KierenConnell** [anonaddy/docker#189]
#### Steps to reproduce this issue

1. Use Docker Compose file

#### Actual behaviour

anonaddy_db reports
`2022-10-22  2:52:19 7 [ERROR] Invalid (old?) table or database name '.gnupg'`

anonaddy reports
```
Creating check_access stored procedure
ERROR 1064 (42000) at line 6: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':' at line 53
[cont-init.d] 15-config-postfix.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
### Configuration

Using the sock docker-compose.yml file
Only changes have been defining passwords

**Comment by crazy-max** [comment]
> Using the sock docker-compose.yml file

Not sure what you mean by "sock"? Can you post your compose file please?

**Comment by KierenConnell** [comment]
Typo. *Stock docker-compose file

```
services:
  db:
    image: mariadb:10.5
    container_name: anonaddy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=**REDACTED**"
      - "MYSQL_USER=**REDACTED**"
      - "MYSQL_PASSWORD=**REDACTED**"
      #- MYSQL_ROOT_PASSWORD=**REDACTED**
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: always

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - db
      - redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
      - target: 8000
        published: 8888
        protocol: tcp
    volumes:
      - ./data:/data
    environment:
      - DB_HOST=db
      - DB_DATABASE=**REDACTED**
      - DB_USERNAME=**REDACTED**
      - DB_PASSWORD=**REDACTED**
      - REDIS_HOST=redis
      - TZ=Europe/London
      - APP_NAME='**REDACTED**'
      - APP_KEY=**REDACTED**
      - APP_URL='**REDACTED**'
      - ANONADDY_DOMAIN='**REDACTED**'
      - ANONADDY_SECRET=**REDACTED**
    restart: always
```
MYSQL_* values and DB_* values are identical
APP_URL & ANONADDY_DOMAIN values are identical
