### ISSUE TITLE
ViewClearCommand.php line 59: Error bootloop

### ISSUE THREAD

**Issue by Smallinger** [anonaddy/docker#242]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/anonaddy/docker/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

got following error

[cont-init.d] 15-config-postfix.sh: exited 0.
[cont-init.d] 50-svc-main.sh: executing... 
DB migration
   INFO  Nothing to migrate.  
Clear cache
   ERROR  Failed to clear cache. Make sure you have the appropriate permissions.  
   INFO  Configuration cached successfully.  
In ViewClearCommand.php line 59:
                        
  View path not found.  
                        
[cont-init.d] 50-svc-main.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

### Expected behaviour

schuld work

### Actual behaviour

not working boot loop

### Steps to reproduce

create docker-compose.yaml
docker compose up

### Docker info

```text
root@Docker:/containers# docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 11
  Paused: 0
  Stopped: 6
 Images: 20
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.16-15-pve
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 8.004GiB
 Name: Docker
 ID: 84b56c75-3dad-45c0-86ea-55aa7b8777f8
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
version: "3"
name: annoaddy
services:
  anonaddy_db:
    image: mariadb:10.5
    container_name: anonaddy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - /containers/anonaddy_data/db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: anonaddy_db
      MYSQL_USER: anonaddy
      MYSQL_PASSWORD: *****************
    restart: unless-stopped
    networks:
      - docker_intern
      
  anonaddy_redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: unless-stopped
    networks:
      - docker_intern

  anonaddy_web:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy_web
    depends_on:
      - anonaddy_db
      - anonaddy_redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - /containers/anonaddy_data/data:/data
    environment:
      DB_HOST: anonaddy_db
      DB_DATABASE: anonaddy_db
      DB_USERNAME: anonaddy
      DB_PASSWORD: *****************
      REDIS_HOST: anonaddy_redis
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
      MEMORY_LIMIT: 256M
      UPLOAD_MAX_SIZE: 16M
      OPCACHE_MEM_SIZE: 128
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      LOG_IP_VAR: remote_addr
      APP_KEY: base64:****************************************
      APP_DEBUG: false
      APP_URL: https://re*********.me
      ## Anonaddy Environment
      ANONADDY_ENABLE_REGISTRATION: true
      ANONADDY_ADMIN_USERNAME: SmallPox
      ANONADDY_DOMAIN: re*********.me
      ANONADDY_ALL_DOMAINS: re*********.me
      ANONADDY_HOSTNAME: mail.re*********.me
      ANONADDY_SECRET: **************************************************
      ANONADDY_LIMIT: 200
      ANONADDY_BANDWIDTH_LIMIT: 104857600
      ANONADDY_NEW_ALIAS_LIMIT: 10
      ANONADDY_ADDITIONAL_USERNAME_LIMIT: 3
      MAIL_FROM_NAME: AnonAddy
      MAIL_FROM_ADDRESS: AnonAddy@re*********.me
      ## Rspamd Environment
     # RSPAMD_ENABLE: true
     # RSPAMD_WEB_PASSWORD: ***************
      ## Postfix Environment
      POSTFIX_DEBUG: false
      POSTFIX_SMTPD_TLS: false
      POSTFIX_SMTP_TLS: false
    restart: unless-stopped
    networks:
      - npm_network
      - docker_intern

networks:
  npm_network:
    external: true
  docker_intern:
    external: true
```

### Logs

```text
[postfix-config] virtual_uid_maps =
Creating check_access stored procedure
[cont-init.d] 15-config-postfix.sh: exited 0.
[cont-init.d] 50-svc-main.sh: executing... 
DB migration
   INFO  Nothing to migrate.  
Clear cache
   ERROR  Failed to clear cache. Make sure you have the appropriate permissions.  
   INFO  Configuration cached successfully.  
In ViewClearCommand.php line 59:
                        
  View path not found.  
                        
[cont-init.d] 50-svc-main.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Additional info

In ViewClearCommand.php line 59:
                        
  View path not found.
