### ISSUE TITLE
500 Error after installation

### ISSUE THREAD

**Issue by marcousa** [anonaddy/docker#274]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/anonaddy/docker/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I installed addy via docker using the template provided and tweaking it.
It installs successfully but when I try to reach the app via [IP]:8000 I get a 500 error and no description in the logs of the docker image for the error: 
"[19/Apr/2024:16:33:21 -0400] "GET / HTTP/1.1" 500 1029 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0""

Here is my compose file:

```YAML
version: "3.5"

services:
  db:
    image: mariadb:10.5
    container_name: anonaddy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "addy_db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=[redacted, but same as DB_DATABASE value]"
      - "MYSQL_USER=[redacted, but same as DB_USERNAME value]"
      - "MYSQL_PASSWORD=[redacted, but same as DB_PASSWORD value]"
      - TZ=America/New_York
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: always

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - db
      - redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - "addy_data:/data"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=[redacted, but same as MYSQL_DATABASE value]"
      - "DB_USERNAME=[redacted, but same as MYSQL_USER value]"
      - "DB_PASSWORD=[redacted, but same as MYSQL_PASSWORD value]"
      - "REDIS_HOST=redis"
      - APP_KEY=[redacted]
      - ANONADDY_SECRET=[redacted]
      - TZ=America/New_York
      - ANONADDY_ADMIN_USERNAME=admin
      - ANONADDY_ENABLE_REGISTRATION=true
      - ANONADDY_DOMAIN=xerxes.me
      - ANONADDY_HOSTNAME=mail.xerxes.me
      - "APP_URL=192.168.4.87:8000"
    restart: always

volumes:
  addy_db:
  addy_data:
```

### Expected behaviour

Going to http://[IP]:8000 should let me reach addy so that I can sign in/up

### Actual behaviour

![image](https://github.com/anonaddy/docker/assets/1309975/9369a344-5e59-4e2f-b91c-e09f47dc9506)

### Steps to reproduce

1. Go to IP:8000 where addy is installed

### Docker info

```text
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.435GiB
 Name: docker-desktop
 ID: 5d0034b2-7618-47c0-bd13-7d68e56ca1e1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Logs

```text
[19/Apr/2024:16:33:21 -0400] "GET / HTTP/1.1" 500 1029 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
```
