### ISSUE TITLE
GPG Key Encryption Error

### ISSUE THREAD

**Issue by hairy-tortoise** [anonaddy/docker#275]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/anonaddy/docker/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Every time I add an GPG Key the first EMail that would have been sent, I get an Your GPG key has expired on addy.io even though it is not.

### Expected behaviour

Encrypt my emails when I provide an valid GPG Key

### Actual behaviour

Your GPG key has expired on addy.io

### Steps to reproduce

1. Install and configure anonaddy using the example
2. Add an GPG Key to an Recipient

### Docker info

```text
Client: Docker Engine - Community
 Version:    26.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 26.0.2
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-9-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 5.787GiB
 Name: [REDACTED]
 ID: a15cad8d-2f50-42b0-bb1c-e524d0ded153
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
name: annoaddy
services:
  addy:
    container_name: addy
    depends_on:
      db:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    environment:
      ANONADDY_ADDITIONAL_USERNAME_LIMIT: "3"
      ANONADDY_ADMIN_USERNAME: [REDACTED]
      ANONADDY_ALL_DOMAINS: [REDACTED]
      ANONADDY_BANDWIDTH_LIMIT: "104857600"
      ANONADDY_DNS_RESOLVER: 127.0.0.1
      ANONADDY_DOMAIN: [REDACTED]
      ANONADDY_ENABLE_REGISTRATION: "false"
      ANONADDY_HOSTNAME: [REDACTED]
      ANONADDY_LIMIT: "200"
      ANONADDY_NEW_ALIAS_LIMIT: "10"
      ANONADDY_RETURN_PATH: [REDACTED]
      ANONADDY_SECRET: [REDACTED]
      APP_DEBUG: "false"
      APP_KEY: [REDACTED]
      APP_URL: [REDACTED]
      DB_DATABASE: addy
      DB_HOST: db
      DB_PASSWORD: [REDACTED]
      DB_USERNAME: addy
      LOG_IP_VAR: remote_addr
      MAIL_FROM_ADDRESS: [REDACTED]
      MAIL_FROM_NAME: [REDACTED]
      MEMORY_LIMIT: 256M
      OPCACHE_MEM_SIZE: "128"
      PGID: "1000"
      POSTFIX_DEBUG: "false"
      POSTFIX_SMTP_TLS: "false"
      POSTFIX_SMTPD_TLS: "false"
      PUID: "1000"
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      REDIS_HOST: redis
      RSPAMD_ENABLE: "true"
      RSPAMD_WEB_PASSWORD: [REDACTED]
      TZ: Europe/Berlin
      UPLOAD_MAX_SIZE: 16M
    image: anonaddy/anonaddy:latest
    networks:
      caddy: null
      default: null
    ports:
      - target: 25
        published: "25"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /root/addy/data
        target: /data
        bind:
          create_host_path: true
  db:
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: addy_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: addy
      MYSQL_PASSWORD: [REDACTED]
      MYSQL_USER: addy
    image: mariadb:10.5
    networks:
      default: null
    restart: always
    volumes:
      - type: bind
        source: /root/addy/db
        target: /var/lib/mysql
        bind:
          create_host_path: true
  redis:
    container_name: addy_redis
    image: redis:4.0-alpine
    networks:
      default: null
    restart: always
networks:
  caddy:
    name: caddy
    external: true
  default:
    name: annoaddy_default
```

### Logs

```text
‎
```
