### ISSUE TITLE
Mail forwarding does no longer work in 0.6.0

### ISSUE THREAD

**Issue by KevinRoebert** [anonaddy/docker#30]
#### Steps to reproduce this issue

1. Do an upgrade as stated in https://github.com/anonaddy/docker#upgrade to version 0.6.0.

#### Expected behavior

Anon should work as before.

#### Actual behaviour

No email is forwarded to the actual inbox. If I downgrade to `anonaddy/anonaddy:0.5.0` everything works again.

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.13, build 4484c46d9d
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.25.0, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 20.04.1 LTS
* System info (type `uname -a`) : Linux 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### docker-compose.yml

```
version: "3.5"

networks:
  proxy:
    external:
      name: proxy_default
  app-network:
      driver: bridge

services:
  db:
    image: mariadb:10.4
    container_name: anonaddy_db
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always
    networks:
      - app-network

  redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: always
    networks:
      - app-network

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - db
      - redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
    volumes:
      - "./data:/data"
    dns:
      - 1.1.1.1
    networks:
      - proxy
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_default"
      - "traefik.http.routers.anon.rule=Host(`anon.example.com`)"
      - "traefik.http.routers.anon.entrypoints=https"
      - "traefik.http.routers.anon.tls.certresolver=http"
      - "traefik.http.routers.anon.middlewares=ratelimit@file,compress@file,security-headers@file"
      - "traefik.http.services.anon.loadbalancer.server.port=8000"
      - "traefik.http.routers.anon.service=anon"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    restart: always
```

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 13
  Paused: 0
  Stopped: 0
 Images: 32
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-45-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.775GiB
 Name: host54.example.com
 ID: V4TL:AQXJ:UBLT:RUIV:TT7X:CUZK:MCRW:4IDG:4W7H:YN4A:AU5I:A6UQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

### Logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-fix-perms.sh: executing...
Fixing perms...
[cont-init.d] 02-fix-perms.sh: exited 0.
[cont-init.d] 03-config.sh: executing...
Setting timezone to Europe/Berlin...
Setting PHP-FPM configuration
Setting PHP INI configuration
Setting OpCache configuration
Setting Nginx configuration
Initializing files and folders
Checking database connection...
Waiting 60s for database to be ready...
Database ready!
Creating AnonAddy env file
Trust all proxies
Copied File [/vendor/fideloper/proxy/config/trustedproxy.php] To [/config/trustedproxy.php]
Publishing complete.
Setting Postfix master configuration
Setting Postfix main configuration
Creating Postfix virtual alias domains and subdomains configuration
Creating Postfix recipient access configuration
Checking Postfix hostname
myhostname = mail.anon.example.com
Creating check_access stored procedure
[cont-init.d] 03-config.sh: exited 0.
[cont-init.d] 04-svc-main.sh: executing...
DB migration
Migrating: 2020_10_07_141852_add_catch_all_to_domains_table
Migrated:  2020_10_07_141852_add_catch_all_to_domains_table (12.11ms)
Migrating: 2020_10_09_115344_add_catch_all_to_additional_usernames_table
Migrated:  2020_10_09_115344_add_catch_all_to_additional_usernames_table (3.93ms)
Migrating: 2020_10_13_091421_add_catch_all_to_users_table
Migrated:  2020_10_13_091421_add_catch_all_to_users_table (3.46ms)
Clear cache
Application cache cleared!
Configuration cache cleared!
Configuration cached successfully!
[cont-init.d] 04-svc-main.sh: exited 0.
[cont-init.d] 05-svc-postfix.sh: executing...
[cont-init.d] 05-svc-postfix.sh: exited 0.
[cont-init.d] 06-svc-cron.sh: executing...
Fixing crontabs permissions...
[cont-init.d] 06-svc-cron.sh: exited 0.
[cont-init.d] 99-clean.sh: executing...
[cont-init.d] 99-clean.sh: exited 0.
[cont-init.d] ~-socklog: executing...
[cont-init.d] ~-socklog: exited 0.
[cont-init.d] done.
[services.d] starting services
crond: crond (busybox 1.31.1) started, log level 8
2020/10/25 14:05:57 [notice] 571#571: using the "epoll" event method
2020/10/25 14:05:57 [notice] 571#571: nginx/1.18.0
2020/10/25 14:05:57 [notice] 571#571: OS: Linux 5.4.0-45-generic
2020/10/25 14:05:57 [notice] 571#571: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2020/10/25 14:05:57 [notice] 571#571: start worker processes
2020/10/25 14:05:57 [notice] 571#571: start worker process 582
2020/10/25 14:05:57 [notice] 571#571: start worker process 583
2020/10/25 14:05:57 [notice] 571#571: start worker process 584
2020/10/25 14:05:57 [notice] 571#571: start worker process 585
2020/10/25 14:05:57 [crit] 584#584: *1 connect() to unix:/var/run/php-fpm/php-fpm7.sock failed (2: No such file or directory) while connecting to upstream, client: 172.22.0.3, server: , request: "GET /login HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm7.sock:", host: "anon.example.com"
31.17.192.74 - - [25/Oct/2020:14:05:57 +0100] "GET /login HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
[services.d] done.
[25-Oct-2020 14:05:57] NOTICE: fpm is running, pid 567
[25-Oct-2020 14:05:57] NOTICE: ready to handle connections
Oct 25 14:05:57 mail postfix/postfix-script[814]: starting the Postfix mail system
Oct 25 14:05:57 mail postfix/master[815]: daemon started -- version 3.5.7, configuration /etc/postfix
31.17.192.74 - - [25/Oct/2020:14:05:59 +0100] "GET /login HTTP/1.1" 200 1389 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
crond: USER anonaddy pid 819 cmd php /var/www/anonaddy/artisan schedule:run --no-ansi --no-interaction --quiet
31.17.192.74 - - [25/Oct/2020:14:06:00 +0100] "POST /login HTTP/1.1" 302 350 "https://anon.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
31.17.192.74 - - [25/Oct/2020:14:06:00 +0100] "GET / HTTP/1.1" 200 1327 "https://anon.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
31.17.192.74 - - [25/Oct/2020:14:06:06 +0100] "POST /login/2fa HTTP/1.1" 302 350 "https://anon.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
31.17.192.74 - - [25/Oct/2020:14:06:06 +0100] "GET / HTTP/1.1" 200 3176 "https://anon.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
Oct 25 14:06:27 mail postfix/smtpd[826]: connect from mout.gmx.net[212.227.15.18]
Oct 25 14:06:27 mail postfix/trivial-rewrite[828]: warning: mysql:/etc/postfix/mysql-virtual-alias-domains-and-subdomains.cf: query failed (mysql_store_result): Subquery returns more than 1 row
Oct 25 14:06:27 mail postfix/trivial-rewrite[828]: warning: virtual_mailbox_domains: mysql:/etc/postfix/mysql-virtual-alias-domains-and-subdomains.cf: table lookup problem
Oct 25 14:06:27 mail postfix/trivial-rewrite[828]: warning: virtual_mailbox_domains lookup failure
Oct 25 14:06:27 mail postfix/trivial-rewrite[828]: warning: virtual_mailbox_domains: mysql:/etc/postfix/mysql-virtual-alias-domains-and-subdomains.cf: table lookup problem
Oct 25 14:06:27 mail postfix/trivial-rewrite[828]: warning: virtual_mailbox_domains lookup failure
Oct 25 14:06:27 mail postfix/smtpd[826]: NOQUEUE: reject: RCPT from mout.gmx.net[212.227.15.18]: 451 4.3.0 <address@gmx.de>: Temporary lookup failure; from=<address@gmx.de> to=<002668cb-8af4-4814-b80c-967980d961b1@anon.example.com> proto=ESMTP helo=<mout.gmx.net>
Oct 25 14:06:27 mail postfix/smtpd[826]: disconnect from mout.gmx.net[212.227.15.18] ehlo=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=3/5
crond: USER anonaddy pid 829 cmd php /var/www/anonaddy/artisan schedule:run --no-ansi --no-interaction --quiet
```
