### ISSUE TITLE
postfix/postlog: fatal: Postfix integrity check failed!

### ISSUE THREAD

**Issue by RobinFrcd** [anonaddy/docker#334]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/anonaddy/docker/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Hi,
So I found a similar issue in the repo, but the person closed it without any comment... https://github.com/anonaddy/docker/issues/333

I recently moved my anonaddy docker deployment to another instance. Before restarting it I made sure to `sudo chown -R 1000:1000 ./data`. 

I'm starting the container with docker-compose, I didn't change any user/group id.
```yaml
  addy:
    image: anonaddy/anonaddy:latest
    container_name: addy
    depends_on:
      - db
      - redis
    ports:
      - "25:25/tcp"
      - "127.0.0.1:8484:8000/tcp"
    volumes:
      - "./data:/data:rw"
    env_file:
      - "./addy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    restart: always
```

The service starts but outputs this error in loop:

```
2025/04/15 10:06:34 [notice] 751#751: start worker process 825
2025/04/15 10:06:34 [notice] 751#751: start worker process 826
2025/04/15 10:06:34 [notice] 751#751: start worker process 827
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
[15-Apr-2025 10:06:35] NOTICE: fpm is running, pid 742
[15-Apr-2025 10:06:35] NOTICE: ready to handle connections
2025-04-15 10:06:35 #749(main) <e9dca5>; main; main: rspamd 3.10.2 is loading configuration, build id: release
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
```

### Expected behaviour

No permissions issues

### Actual behaviour

```
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
```

### Steps to reproduce

Move a working docker volumes to another instance, and restart the instance.

### Docker info

```text
Client: Docker Engine - Community
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 17
  Paused: 0
  Stopped: 0
 Images: 45
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-34-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.65GiB
 Name: ns3292359
 ID: RJH4:VNMN:AS7Q:6L4M:UMAW:CELN:W44Z:JNGH:HYZV:WF6U:T3RF:CZEI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
name: addy

services:
  db:
    image: mariadb:10
    container_name: addy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: addy_redis
    restart: always

  addy:
    image: anonaddy/anonaddy:latest
    container_name: addy
    depends_on:
      - db
      - redis
    ports:
      - "25:25/tcp"
      - "127.0.0.1:8484:8000/tcp"
    volumes:
      - "./data:/data:rw"
    env_file:
      - "./addy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    restart: always
```

### Logs

```text
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
postfix/postlog: fatal: Postfix integrity check failed!
postsuper: fatal: scan_dir_push: open directory defer: Permission denied
```
