### ISSUE TITLE
500 error while adding public key

### ISSUE THREAD

**Issue by LivingWithHippos** [anonaddy/docker#34]
### Behaviour

I get an error while adding my public GPG key to anonaddy.

#### Steps to reproduce this issue

0. Generated a gpg key following [this](https://www.linuxbabe.com/security/a-practical-guide-to-gpg-part-1-generate-your-keypair)
1. Click on add public key
2. Adding this from my generated key

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBF+xWfABDADeNU+eGhOUNkVVanVYVmrehuR7HjQe+X/HuQoFIWcglZnLP0Iw
/p1hMXhnvgvqQRRLtQ23hWwG5uhs5jOeAlAry2LJ1fTnmUfTwBqVKMcFwazGf1bc
...
zEMMkNT4EGh8c64hk0jvOO4=
=E2E0
-----END PGP PUBLIC KEY BLOCK-----
```

#### Expected behaviour

The key is added

#### Actual behaviour

I get a generic error popup

```
Error
{ "message": "Server Error" }
```

My emails are not encrypted and are sent to the spam folder by gmail, I hope that by solving this they'll stop getting blacklisted...

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.13, build 4484c46d9d
* Docker compose version if applicable (type `docker-compose --version`) :  docker-compose version 1.26.0, build d4451659
* Platform (Debian 9, Ubuntu 18.04, ...) : ubuntu 20
* System info (type `uname -a`) :  Linux v2202005122621119251 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Logs

`[15/Nov/2020:18:55:24 +0100] "PATCH /api/v1/recipient-keys/8d9665cd-5a26-4fda-8c3b-9e06d5374c5d HTTP/1.1" 500 44 "https://mail.domain.tld/recipients" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0"`

docker-compose.yml

```yaml
version: "3.5"

services:
  db:
    image: mariadb:10.4
    container_name: anonaddy_db
    volumes:
      - "/data/anonaddy/db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: unless-stopped

  redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: unless-stopped

  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    depends_on:
      - db
      - redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
#      - target: 8000
#        published: 8000
#        protocol: tcp
    volumes:
      - "/data/anonaddy/data:/data"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    restart: unless-stopped

```

anonaddy.env (partial)

```python
TZ=Europe/Berlin
PUID=1000
PGID=1000

MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

APP_KEY=base64:generated key
APP_DEBUG=false
APP_URL=mail.domain.tld

ANONADDY_RETURN_PATH=mail@domain.tld
ANONADDY_DOMAIN=domain.tld
ANONADDY_ALL_DOMAINS=domain.tld
ANONADDY_HOSTNAME=mail.domain.tld
ANONADDY_DNS_RESOLVER=127.0.0.1
ANONADDY_SECRET=random string. I'd like some pointers on this
ANONADDY_LIMIT=200
ANONADDY_BANDWIDTH_LIMIT=104857600
ANONADDY_NEW_ALIAS_LIMIT=10
ANONADDY_ADDITIONAL_USERNAME_LIMIT=3
ANONADDY_SIGNING_KEY_FINGERPRINT=gpg short signature

MAIL_FROM_NAME=Admin
MAIL_FROM_ADDRESS=mail@domain.tld

POSTFIX_DEBUG=false
POSTFIX_SMTPD_TLS=false
POSTFIX_SMTP_TLS=false
```
