### ISSUE TITLE
secondary domains added via GUI not being signed by DKIM

### ISSUE THREAD

**Issue by dgc1980** [anonaddy/docker#77]
#### Steps to reproduce this issue

1. add `ANONADDY_DKIM_SIGNING_KEY=/data/dkim/domain.com.private` to .env as per self-install wiki to allow signing of additional domains
2. add additional domain via UI
3. create new alias under said domain
4. send test email to said alias

#### Expected behaviour

> DKIM signing of outgoing emails

#### Actual behaviour

> mail.info: Aug  9 20:54:09 opendkim[681]: 07C80A4647: no signing table match for '15a03b0d-24b7-4dc6-a265-xxxxxx@xxxxxx'

### Configuration

* Docker version (type `docker --version`) :
- `Docker version 20.10.7, build f0df350`
* Docker compose version if applicable (type `docker-compose --version`) : 
- `docker-compose version 1.25.0, build unknown`
* Platform (Debian 9, Ubuntu 18.04, ...) : 
- `Ubuntu 20.04`
* System info (type `uname -a`) : 
- `Linux mail.xxxxx.com 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

```
version: "3.5"

services:
  traefik:
    image: traefik:2.3
    container_name: traefik
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=webmaster@XXXXXX.com"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--providers.docker"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  db:
    image: mariadb:10.5
    container_name: anonaddy_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=XXXX"
      - "MYSQL_USER=XXXX"
      - "MYSQL_PASSWORD=XXXX"
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: anonaddy_redis
    restart: always

  anonaddy:
    #image: anonaddy/anonaddy:latest
    image: anonaddy/anonaddy:pr-76
    container_name: anonaddy
    depends_on:
      - db
      - redis
    ports:
      - target: 25
        published: 25
        protocol: tcp
    volumes:
      - "./data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anonaddy.entrypoints=https"
      - "traefik.http.routers.anonaddy.rule=Host(`anonaddy.XXXXXX.com`)"
      - "traefik.http.routers.anonaddy.tls=true"
      - "traefik.http.routers.anonaddy.tls.certresolver=letsencrypt"
      - "traefik.http.routers.anonaddy.tls.domains[0].main=anonaddy.XXXXXX.com"
      - "traefik.http.services.anonaddy.loadbalancer.server.port=8000"
    env_file:
      - "./anonaddy.env"
    environment:
      - "DB_HOST=db"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "REDIS_HOST=redis"
    restart: always
```

```
TZ=Australia/Melbourne
PUID=1000
PGID=1000

MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=http_x_forwarded_for

APP_KEY=XXXXXX
APP_DEBUG=false
APP_URL=https://anonaddy.XXXXXX.com

ANONADDY_RETURN_PATH=bounces@XXXXXX.com
ANONADDY_ADMIN_USERNAME=dgc1980
ANONADDY_ENABLE_REGISTRATION=false
ANONADDY_DOMAIN=XXXXXX.com
ANONADDY_ALL_DOMAINS=XXXXXX.com
ANONADDY_HOSTNAME=anonaddy.XXXXXX.com
ANONADDY_DNS_RESOLVER=1.1.1.1
ANONADDY_SECRET=XXXXXX
ANONADDY_LIMIT=50
ANONADDY_BANDWIDTH_LIMIT=1073741824
#ANONADDY_BANDWIDTH_LIMIT=104857600
ANONADDY_NEW_ALIAS_LIMIT=20
ANONADDY_ADDITIONAL_USERNAME_LIMIT=3
#ANONADDY_SIGNING_KEY_FINGERPRINT=XXXXXX
ANONADDY_DKIM_SIGNING_KEY=/data/dkim/XXXXXX.com.private
#ANONADDY_DKIM_SIGNING_KEY=/var/db/dkim/XXXXXX.com.private
#ANONADDY_DKIM_SIGNING_KEY=/data/dkim/XXXXXX.com.txt

DKIM_ENABLE=true

MAIL_FROM_NAME=AnonAddy
MAIL_FROM_ADDRESS=anonaddy@XXXXXX.com

POSTFIX_DEBUG=false
POSTFIX_SMTPD_TLS=false
POSTFIX_SMTP_TLS=false
```

### Docker info

```
> Output of command `docker info`
```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```
