### ISSUE TITLE
[enhancement] allow for optional use of rspamd (instead of opendkim / opendmarc)

### ISSUE THREAD

**Issue by eleith** [anonaddy/docker#93]
opendkim and opendmarc are used for dmarc/dkim verification.

however, [anonaddy self hosting docs](https://anonaddy.com/self-hosting/) suggests rspamd as an alternative.

this alternative may be valuable to some users since opendkim  (mostly unmaintained as this point in time) actually behaves differently in alpine vs other OSes like debian. because of the different glibc compiler in alpine, i've been able to reproduce a number of dkim verification failures that only occur when using the alpine container.

rspamd is a bit more current, aligned with anonaddy's own documentation, works in an alpine container and integrates nicely as a side car container if you use `docker-compose`.

the following modifications are needed to implement this suggestion:

1. using `mailprotector/rspamd` image in coordination with the [other containers](https://github.com/anonaddy/docker/blob/master/examples/compose/docker-compose.yml)

```yaml
  rspamd:
    image: mailprotector/rspamd:0.1
    container_name: anonaddy_rspamd
    restart: unless-stopped
    volumes:
      - ./data/rspamd:/etc/rspamd/override.d
      - ./data/dkim:/etc/dkim
    environment:
      - RSPAMD_ARC_ENABLE=true
      - RSPAMD_DKIM_SIGNING_ENABLE=true
      - RSPAMD_GREYLIST_ENABLE=true
      - RSPAMD_LOG_LEVEL=error
      - RSPAMD_REDIS_SERVERS=redis
      - RSPAMD_WEBUI_PASSWORD= xyz           
    depends_on:
      - anonaddy
      - redis
```

2. turn off opendkim/opendmarc in anonaddy.env

```
DKIM_ENABLE=false
DMARC_ENABLE=false
```

3. manually modifying smtpd milter to point to rspamd in `postfix/main.cf` as described in [anonaddy's self hosted doc](https://anonaddy.com/self-hosting/)

```
# Milter configuration
milter_default_action = accept
milter_protocol = 6
smtpd_milters = inet:rspamd:11332
non_smtpd_milters = $smtpd_milters
milter_mail_macros =  i {mail_addr} {client_addr} {client_name} {auth_authen}
```

4. add all the files suggested in the self hosted docs with the correct domains and with proper access to the dkim keys. below is one such example for `./data/rspamd/dkim_signing.conf` 

```
signing_table = [
"*@example.com example.com",
"*@*.example.com example.com",
];

key_table = [
"example.com example.com:default:/etc/rspamd/override.d/dkim/example.com.default.key",
];

use_domain = "envelope";
allow_hdrfrom_mismatch = true;
allow_hdrfrom_mismatch_sign_networks = true;
allow_username_mismatch = true;
use_esld = true;
sign_authenticated = false;
```
